<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ["name" => "Afghanistan", "iso_code" => "AF", "phone_code" => "+93", "phone_digits" => 9, "flag" => "🇦🇫"],
            ["name" => "Albania", "iso_code" => "AL", "phone_code" => "+355", "phone_digits" => 9, "flag" => "🇦🇱"],
            ["name" => "Algeria", "iso_code" => "DZ", "phone_code" => "+213", "phone_digits" => 9, "flag" => "🇩🇿"],
            ["name" => "American Samoa", "iso_code" => "AS", "phone_code" => "+1684", "phone_digits" => 7, "flag" => "🇦🇸"],
            ["name" => "Andorra", "iso_code" => "AD", "phone_code" => "+376", "phone_digits" => 6, "flag" => "🇦🇩"],
            ["name" => "Angola", "iso_code" => "AO", "phone_code" => "+244", "phone_digits" => 9, "flag" => "🇦🇴"],
            ["name" => "Anguilla", "iso_code" => "AI", "phone_code" => "+1264", "phone_digits" => 7, "flag" => "🇦🇮"],
            ["name" => "Antigua and Barbuda", "iso_code" => "AG", "phone_code" => "+1268", "phone_digits" => 7, "flag" => "🇦🇬"],
            ["name" => "Argentina", "iso_code" => "AR", "phone_code" => "+54", "phone_digits" => 10, "flag" => "🇦🇷"],
            ["name" => "Armenia", "iso_code" => "AM", "phone_code" => "+374", "phone_digits" => 8, "flag" => "🇦🇲"],
            ["name" => "Aruba", "iso_code" => "AW", "phone_code" => "+297", "phone_digits" => 7, "flag" => "🇦🇼"],
            ["name" => "Australia", "iso_code" => "AU", "phone_code" => "+61", "phone_digits" => 9, "flag" => "🇦🇺"],
            ["name" => "Austria", "iso_code" => "AT", "phone_code" => "+43", "phone_digits" => 10, "flag" => "🇦🇹"],
            ["name" => "Azerbaijan", "iso_code" => "AZ", "phone_code" => "+994", "phone_digits" => 9, "flag" => "🇦🇿"],
            ["name" => "Bahamas", "iso_code" => "BS", "phone_code" => "+1242", "phone_digits" => 7, "flag" => "🇧🇸"],
            ["name" => "Bahrain", "iso_code" => "BH", "phone_code" => "+973", "phone_digits" => 8, "flag" => "🇧🇭"],
            ["name" => "Bangladesh", "iso_code" => "BD", "phone_code" => "+880", "phone_digits" => 10, "flag" => "🇧🇩"],
            ["name" => "Barbados", "iso_code" => "BB", "phone_code" => "+1246", "phone_digits" => 7, "flag" => "🇧🇧"],
            ["name" => "Belarus", "iso_code" => "BY", "phone_code" => "+375", "phone_digits" => 9, "flag" => "🇧🇾"],
            ["name" => "Belgium", "iso_code" => "BE", "phone_code" => "+32", "phone_digits" => 9, "flag" => "🇧🇪"],
            ["name" => "Belize", "iso_code" => "BZ", "phone_code" => "+501", "phone_digits" => 7, "flag" => "🇧🇿"],
            ["name" => "Benin", "iso_code" => "BJ", "phone_code" => "+229", "phone_digits" => 8, "flag" => "🇧🇯"],
            ["name" => "Bermuda", "iso_code" => "BM", "phone_code" => "+1441", "phone_digits" => 7, "flag" => "🇧🇲"],
            ["name" => "Bhutan", "iso_code" => "BT", "phone_code" => "+975", "phone_digits" => 8, "flag" => "🇧🇹"],
            ["name" => "Bolivia", "iso_code" => "BO", "phone_code" => "+591", "phone_digits" => 8, "flag" => "🇧🇴"],
            ["name" => "Bosnia and Herzegovina", "iso_code" => "BA", "phone_code" => "+387", "phone_digits" => 8, "flag" => "🇧🇦"],
            ["name" => "Botswana", "iso_code" => "BW", "phone_code" => "+267", "phone_digits" => 8, "flag" => "🇧🇼"],
            ["name" => "Brazil", "iso_code" => "BR", "phone_code" => "+55", "phone_digits" => 11, "flag" => "🇧🇷"],
            ["name" => "British Virgin Islands", "iso_code" => "VG", "phone_code" => "+1284", "phone_digits" => 7, "flag" => "🇻🇬"],
            ["name" => "Brunei", "iso_code" => "BN", "phone_code" => "+673", "phone_digits" => 7, "flag" => "🇧🇳"],
            ["name" => "Bulgaria", "iso_code" => "BG", "phone_code" => "+359", "phone_digits" => 9, "flag" => "🇧🇬"],
            ["name" => "Burkina Faso", "iso_code" => "BF", "phone_code" => "+226", "phone_digits" => 8, "flag" => "🇧🇫"],
            ["name" => "Burundi", "iso_code" => "BI", "phone_code" => "+257", "phone_digits" => 8, "flag" => "🇧🇮"],
            ["name" => "Cambodia", "iso_code" => "KH", "phone_code" => "+855", "phone_digits" => 9, "flag" => "🇰🇭"],
            ["name" => "Cameroon", "iso_code" => "CM", "phone_code" => "+237", "phone_digits" => 9, "flag" => "🇨🇲"],
            ["name" => "Canada", "iso_code" => "CA", "phone_code" => "+1", "phone_digits" => 10, "flag" => "🇨🇦"],
            ["name" => "Cape Verde", "iso_code" => "CV", "phone_code" => "+238", "phone_digits" => 7, "flag" => "🇨🇻"],
            ["name" => "Cayman Islands", "iso_code" => "KY", "phone_code" => "+1345", "phone_digits" => 7, "flag" => "🇰🇾"],
            ["name" => "Central African Republic", "iso_code" => "CF", "phone_code" => "+236", "phone_digits" => 8, "flag" => "🇨🇫"],
            ["name" => "Chad", "iso_code" => "TD", "phone_code" => "+235", "phone_digits" => 8, "flag" => "🇹🇩"],
            ["name" => "Chile", "iso_code" => "CL", "phone_code" => "+56", "phone_digits" => 9, "flag" => "🇨🇱"],
            ["name" => "China", "iso_code" => "CN", "phone_code" => "+86", "phone_digits" => 11, "flag" => "🇨🇳"],
            ["name" => "Colombia", "iso_code" => "CO", "phone_code" => "+57", "phone_digits" => 10, "flag" => "🇨🇴"],
            ["name" => "Comoros", "iso_code" => "KM", "phone_code" => "+269", "phone_digits" => 7, "flag" => "🇰🇲"],
            ["name" => "Cook Islands", "iso_code" => "CK", "phone_code" => "+682", "phone_digits" => 5, "flag" => "🇨🇰"],
            ["name" => "Costa Rica", "iso_code" => "CR", "phone_code" => "+506", "phone_digits" => 8, "flag" => "🇨🇷"],
            ["name" => "Croatia", "iso_code" => "HR", "phone_code" => "+385", "phone_digits" => 9, "flag" => "🇭🇷"],
            ["name" => "Cuba", "iso_code" => "CU", "phone_code" => "+53", "phone_digits" => 8, "flag" => "🇨🇺"],
            ["name" => "Cyprus", "iso_code" => "CY", "phone_code" => "+357", "phone_digits" => 8, "flag" => "🇨🇾"],
            ["name" => "Czech Republic", "iso_code" => "CZ", "phone_code" => "+420", "phone_digits" => 9, "flag" => "🇨🇿"],
            ["name" => "Democratic Republic of the Congo", "iso_code" => "CD", "phone_code" => "+243", "phone_digits" => 9, "flag" => "🇨🇩"],
            ["name" => "Denmark", "iso_code" => "DK", "phone_code" => "+45", "phone_digits" => 8, "flag" => "🇩🇰"],
            ["name" => "Djibouti", "iso_code" => "DJ", "phone_code" => "+253", "phone_digits" => 8, "flag" => "🇩🇯"],
            ["name" => "Dominica", "iso_code" => "DM", "phone_code" => "+1767", "phone_digits" => 7, "flag" => "🇩🇲"],
            ["name" => "Dominican Republic", "iso_code" => "DO", "phone_code" => "+1809", "phone_digits" => 10, "flag" => "🇩🇴"],
            ["name" => "East Timor", "iso_code" => "TL", "phone_code" => "+670", "phone_digits" => 7, "flag" => "🇹🇱"],
            ["name" => "Ecuador", "iso_code" => "EC", "phone_code" => "+593", "phone_digits" => 9, "flag" => "🇪🇨"],
            ["name" => "Egypt", "iso_code" => "EG", "phone_code" => "+20", "phone_digits" => 10, "flag" => "🇪🇬"],
            ["name" => "El Salvador", "iso_code" => "SV", "phone_code" => "+503", "phone_digits" => 8, "flag" => "🇸🇻"],
            ["name" => "Equatorial Guinea", "iso_code" => "GQ", "phone_code" => "+240", "phone_digits" => 9, "flag" => "🇬🇶"],
            ["name" => "Eritrea", "iso_code" => "ER", "phone_code" => "+291", "phone_digits" => 7, "flag" => "🇪🇷"],
            ["name" => "Estonia", "iso_code" => "EE", "phone_code" => "+372", "phone_digits" => 8, "flag" => "🇪🇪"],
            ["name" => "Ethiopia", "iso_code" => "ET", "phone_code" => "+251", "phone_digits" => 9, "flag" => "🇪🇹"],
            ["name" => "Falkland Islands", "iso_code" => "FK", "phone_code" => "+500", "phone_digits" => 5, "flag" => "🇫🇰"],
            ["name" => "Faroe Islands", "iso_code" => "FO", "phone_code" => "+298", "phone_digits" => 6, "flag" => "🇫🇴"],
            ["name" => "Fiji", "iso_code" => "FJ", "phone_code" => "+679", "phone_digits" => 7, "flag" => "🇫🇯"],
            ["name" => "Finland", "iso_code" => "FI", "phone_code" => "+358", "phone_digits" => 9, "flag" => "🇫🇮"],
            ["name" => "France", "iso_code" => "FRA", "phone_code" => "+33", "phone_digits" => 9, "flag" => "🇫🇷"],
            ["name" => "French Guiana", "iso_code" => "GF", "phone_code" => "+594", "phone_digits" => 9, "flag" => "🇬🇫"],
            ["name" => "French Polynesia", "iso_code" => "PF", "phone_code" => "+689", "phone_digits" => 6, "flag" => "🇵🇫"],
            ["name" => "Gabon", "iso_code" => "GA", "phone_code" => "+241", "phone_digits" => 8, "flag" => "🇬🇦"],
            ["name" => "Gambia", "iso_code" => "GM", "phone_code" => "+220", "phone_digits" => 7, "flag" => "🇬🇲"],
            ["name" => "Georgia", "iso_code" => "GE", "phone_code" => "+995", "phone_digits" => 9, "flag" => "🇬🇪"],
            ["name" => "Germany", "iso_code" => "DE", "phone_code" => "+49", "phone_digits" => 10, "flag" => "🇩🇪"],
            ["name" => "Ghana", "iso_code" => "GH", "phone_code" => "+233", "phone_digits" => 9, "flag" => "🇬🇭"],
            ["name" => "Gibraltar", "iso_code" => "GI", "phone_code" => "+350", "phone_digits" => 8, "flag" => "🇬🇮"],
            ["name" => "Greece", "iso_code" => "GR", "phone_code" => "+30", "phone_digits" => 10, "flag" => "🇬🇷"],
            ["name" => "Greenland", "iso_code" => "GL", "phone_code" => "+299", "phone_digits" => 6, "flag" => "🇬🇱"],
            ["name" => "Grenada", "iso_code" => "GD", "phone_code" => "+1473", "phone_digits" => 7, "flag" => "🇬🇩"],
            ["name" => "Guadeloupe", "iso_code" => "GP", "phone_code" => "+590", "phone_digits" => 9, "flag" => "🇬🇵"],
            ["name" => "Guam", "iso_code" => "GU", "phone_code" => "+1671", "phone_digits" => 7, "flag" => "🇬🇺"],
            ["name" => "Guatemala", "iso_code" => "GT", "phone_code" => "+502", "phone_digits" => 8, "flag" => "🇬🇹"],
            ["name" => "Guinea", "iso_code" => "GN", "phone_code" => "+224", "phone_digits" => 9, "flag" => "🇬🇳"],
            ["name" => "Guinea-Bissau", "iso_code" => "GW", "phone_code" => "+245", "phone_digits" => 7, "flag" => "🇬🇼"],
            ["name" => "Guyana", "iso_code" => "GY", "phone_code" => "+592", "phone_digits" => 7, "flag" => "🇬🇾"],
            ["name" => "Haiti", "iso_code" => "HT", "phone_code" => "+509", "phone_digits" => 8, "flag" => "🇭🇹"],
            ["name" => "Honduras", "iso_code" => "HN", "phone_code" => "+504", "phone_digits" => 8, "flag" => "🇭🇳"],
            ["name" => "Hong Kong", "iso_code" => "HK", "phone_code" => "+852", "phone_digits" => 8, "flag" => "🇭🇰"],
            ["name" => "Hungary", "iso_code" => "HU", "phone_code" => "+36", "phone_digits" => 9, "flag" => "🇭🇺"],
            ["name" => "Iceland", "iso_code" => "IS", "phone_code" => "+354", "phone_digits" => 7, "flag" => "🇮🇸"],
            ["name" => "India", "iso_code" => "IN", "phone_code" => "+91", "phone_digits" => 10, "flag" => "🇮🇳"],
            ["name" => "Indonesia", "iso_code" => "ID", "phone_code" => "+62", "phone_digits" => 10, "flag" => "🇮🇩"],
            ["name" => "Iran", "iso_code" => "IR", "phone_code" => "+98", "phone_digits" => 10, "flag" => "🇮🇷"],
            ["name" => "Iraq", "iso_code" => "IQ", "phone_code" => "+964", "phone_digits" => 10, "flag" => "🇮🇶"],
            ["name" => "Ireland", "iso_code" => "IE", "phone_code" => "+353", "phone_digits" => 9, "flag" => "🇮🇪"],
            ["name" => "Israel", "iso_code" => "IL", "phone_code" => "+972", "phone_digits" => 9, "flag" => "🇮🇱"],
            ["name" => "Italy", "iso_code" => "IT", "phone_code" => "+39", "phone_digits" => 10, "flag" => "🇮🇹"],
            ["name" => "Ivory Coast", "iso_code" => "CI", "phone_code" => "+225", "phone_digits" => 8, "flag" => "🇨🇮"],
            ["name" => "Jamaica", "iso_code" => "JM", "phone_code" => "+1876", "phone_digits" => 7, "flag" => "🇯🇲"],
            ["name" => "Japan", "iso_code" => "JP", "phone_code" => "+81", "phone_digits" => 10, "flag" => "🇯🇵"],
            ["name" => "Jordan", "iso_code" => "JO", "phone_code" => "+962", "phone_digits" => 9, "flag" => "🇯🇴"],
            ["name" => "Kazakhstan", "iso_code" => "KZ", "phone_code" => "+7", "phone_digits" => 10, "flag" => "🇰🇿"],
            ["name" => "Kenya", "iso_code" => "KE", "phone_code" => "+254", "phone_digits" => 9, "flag" => "🇰🇪"],
            ["name" => "Kiribati", "iso_code" => "KI", "phone_code" => "+686", "phone_digits" => 8, "flag" => "🇰🇮"],
            ["name" => "Kosovo", "iso_code" => "XK", "phone_code" => "+383", "phone_digits" => 8, "flag" => "🇽🇰"],
            ["name" => "Kuwait", "iso_code" => "KW", "phone_code" => "+965", "phone_digits" => 8, "flag" => "🇰🇼"],
            ["name" => "Kyrgyzstan", "iso_code" => "KG", "phone_code" => "+996", "phone_digits" => 9, "flag" => "🇰🇬"],
            ["name" => "Laos", "iso_code" => "LA", "phone_code" => "+856", "phone_digits" => 10, "flag" => "🇱🇦"],
            ["name" => "Latvia", "iso_code" => "LV", "phone_code" => "+371", "phone_digits" => 8, "flag" => "🇱🇻"],
            ["name" => "Lebanon", "iso_code" => "LB", "phone_code" => "+961", "phone_digits" => 8, "flag" => "🇱🇧"],
            ["name" => "Lesotho", "iso_code" => "LS", "phone_code" => "+266", "phone_digits" => 8, "flag" => "🇱🇸"],
            ["name" => "Liberia", "iso_code" => "LR", "phone_code" => "+231", "phone_digits" => 7, "flag" => "🇱🇷"],
            ["name" => "Libya", "iso_code" => "LY", "phone_code" => "+218", "phone_digits" => 9, "flag" => "🇱🇾"],
            ["name" => "Liechtenstein", "iso_code" => "LI", "phone_code" => "+423", "phone_digits" => 7, "flag" => "🇱🇮"],
            ["name" => "Lithuania", "iso_code" => "LT", "phone_code" => "+370", "phone_digits" => 8, "flag" => "🇱🇹"],
            ["name" => "Luxembourg", "iso_code" => "LU", "phone_code" => "+352", "phone_digits" => 9, "flag" => "🇱🇺"],
            ["name" => "Macau", "iso_code" => "MO", "phone_code" => "+853", "phone_digits" => 8, "flag" => "🇲🇴"],
            ["name" => "Madagascar", "iso_code" => "MG", "phone_code" => "+261", "phone_digits" => 9, "flag" => "🇲🇬"],
            ["name" => "Malawi", "iso_code" => "MW", "phone_code" => "+265", "phone_digits" => 9, "flag" => "🇲🇼"],
            ["name" => "Malaysia", "iso_code" => "MY", "phone_code" => "+60", "phone_digits" => 9, "flag" => "🇲🇾"],
            ["name" => "Maldives", "iso_code" => "MV", "phone_code" => "+960", "phone_digits" => 7, "flag" => "🇲🇻"],
            ["name" => "Mali", "iso_code" => "ML", "phone_code" => "+223", "phone_digits" => 8, "flag" => "🇲🇱"],
            ["name" => "Malta", "iso_code" => "MT", "phone_code" => "+356", "phone_digits" => 8, "flag" => "🇲🇹"],
            ["name" => "Marshall Islands", "iso_code" => "MH", "phone_code" => "+692", "phone_digits" => 7, "flag" => "🇲🇭"],
            ["name" => "Martinique", "iso_code" => "MQ", "phone_code" => "+596", "phone_digits" => 9, "flag" => "🇲🇶"],
            ["name" => "Mauritania", "iso_code" => "MR", "phone_code" => "+222", "phone_digits" => 8, "flag" => "🇲🇷"],
            ["name" => "Mauritius", "iso_code" => "MU", "phone_code" => "+230", "phone_digits" => 7, "flag" => "🇲🇺"],
            ["name" => "Mexico", "iso_code" => "MX", "phone_code" => "+52", "phone_digits" => 10, "flag" => "🇲🇽"],
            ["name" => "Micronesia", "iso_code" => "FM", "phone_code" => "+691", "phone_digits" => 7, "flag" => "🇫🇲"],
            ["name" => "Moldova", "iso_code" => "MD", "phone_code" => "+373", "phone_digits" => 8, "flag" => "🇲🇩"],
            ["name" => "Monaco", "iso_code" => "MC", "phone_code" => "+377", "phone_digits" => 8, "flag" => "🇲🇨"],
            ["name" => "Mongolia", "iso_code" => "MN", "phone_code" => "+976", "phone_digits" => 8, "flag" => "🇲🇳"],
            ["name" => "Montenegro", "iso_code" => "ME", "phone_code" => "+382", "phone_digits" => 8, "flag" => "🇲🇪"],
            ["name" => "Montserrat", "iso_code" => "MS", "phone_code" => "+1664", "phone_digits" => 7, "flag" => "🇲🇸"],
            ["name" => "Morocco", "iso_code" => "MA", "phone_code" => "+212", "phone_digits" => 9, "flag" => "🇲🇦"],
            ["name" => "Mozambique", "iso_code" => "MZ", "phone_code" => "+258", "phone_digits" => 8, "flag" => "🇲🇿"],
            ["name" => "Myanmar", "iso_code" => "MM", "phone_code" => "+95", "phone_digits" => 9, "flag" => "🇲🇲"],
            ["name" => "Namibia", "iso_code" => "NA", "phone_code" => "+264", "phone_digits" => 8, "flag" => "🇳🇦"],
            ["name" => "Nauru", "iso_code" => "NR", "phone_code" => "+674", "phone_digits" => 7, "flag" => "🇳🇷"],
            ["name" => "Nepal", "iso_code" => "NP", "phone_code" => "+977", "phone_digits" => 10, "flag" => "🇳🇵"],
            ["name" => "Netherlands", "iso_code" => "NL", "phone_code" => "+31", "phone_digits" => 9, "flag" => "🇳🇱"],
            ["name" => "New Caledonia", "iso_code" => "NC", "phone_code" => "+687", "phone_digits" => 6, "flag" => "🇳🇨"],
            ["name" => "New Zealand", "iso_code" => "NZ", "phone_code" => "+64", "phone_digits" => 8, "flag" => "🇳🇿"],
            ["name" => "Nicaragua", "iso_code" => "NI", "phone_code" => "+505", "phone_digits" => 8, "flag" => "🇳🇮"],
            ["name" => "Niger", "iso_code" => "NE", "phone_code" => "+227", "phone_digits" => 8, "flag" => "🇳🇪"],
            ["name" => "Nigeria", "iso_code" => "NG", "phone_code" => "+234", "phone_digits" => 10, "flag" => "🇳🇬"],
            ["name" => "Niue", "iso_code" => "NU", "phone_code" => "+683", "phone_digits" => 4, "flag" => "🇳🇺"],
            ["name" => "North Korea", "iso_code" => "KP", "phone_code" => "+850", "phone_digits" => 10, "flag" => "🇰🇵"],
            ["name" => "Northern Mariana Islands", "iso_code" => "MP", "phone_code" => "+1670", "phone_digits" => 7, "flag" => "🇲🇵"],
            ["name" => "Norway", "iso_code" => "NO", "phone_code" => "+47", "phone_digits" => 8, "flag" => "🇳🇴"],
            ["name" => "Oman", "iso_code" => "OM", "phone_code" => "+968", "phone_digits" => 8, "flag" => "🇴🇲"],
            ["name" => "Pakistan", "iso_code" => "PK", "phone_code" => "+92", "phone_digits" => 10, "flag" => "🇵🇰"],
            ["name" => "Palau", "iso_code" => "PW", "phone_code" => "+680", "phone_digits" => 7, "flag" => "🇵🇼"],
            ["name" => "Palestine", "iso_code" => "PS", "phone_code" => "+970", "phone_digits" => 9, "flag" => "🇵🇸"],
            ["name" => "Panama", "iso_code" => "PA", "phone_code" => "+507", "phone_digits" => 8, "flag" => "🇵🇦"],
            ["name" => "Papua New Guinea", "iso_code" => "PG", "phone_code" => "+675", "phone_digits" => 8, "flag" => "🇵🇬"],
            ["name" => "Paraguay", "iso_code" => "PY", "phone_code" => "+595", "phone_digits" => 9, "flag" => "🇵🇾"],
            ["name" => "Peru", "iso_code" => "PE", "phone_code" => "+51", "phone_digits" => 9, "flag" => "🇵🇪"],
            ["name" => "Philippines", "iso_code" => "PH", "phone_code" => "+63", "phone_digits" => 10, "flag" => "🇵🇭"],
            ["name" => "Poland", "iso_code" => "PL", "phone_code" => "+48", "phone_digits" => 9, "flag" => "🇵🇱"],
            ["name" => "Portugal", "iso_code" => "PT", "phone_code" => "+351", "phone_digits" => 9, "flag" => "🇵🇹"],
            ["name" => "Puerto Rico", "iso_code" => "PR", "phone_code" => "+1787", "phone_digits" => 10, "flag" => "🇵🇷"],
            ["name" => "Qatar", "iso_code" => "QA", "phone_code" => "+974", "phone_digits" => 8, "flag" => "🇶🇦"],
            ["name" => "Republic of the Congo", "iso_code" => "CG", "phone_code" => "+242", "phone_digits" => 9, "flag" => "🇨🇬"],
            ["name" => "Romania", "iso_code" => "RO", "phone_code" => "+40", "phone_digits" => 9, "flag" => "🇷🇴"],
            ["name" => "Russia", "iso_code" => "RU", "phone_code" => "+7", "phone_digits" => 10, "flag" => "🇷🇺"],
            ["name" => "Rwanda", "iso_code" => "RW", "phone_code" => "+250", "phone_digits" => 9, "flag" => "🇷🇼"],
            ["name" => "Saint Kitts and Nevis", "iso_code" => "KN", "phone_code" => "+1869", "phone_digits" => 7, "flag" => "🇰🇳"],
            ["name" => "Saint Lucia", "iso_code" => "LC", "phone_code" => "+1758", "phone_digits" => 7, "flag" => "🇱🇨"],
            ["name" => "Saint Vincent and the Grenadines", "iso_code" => "VC", "phone_code" => "+1784", "phone_digits" => 7, "flag" => "🇻🇨"],
            ["name" => "Samoa", "iso_code" => "WS", "phone_code" => "+685", "phone_digits" => 7, "flag" => "🇼🇸"],
            ["name" => "San Marino", "iso_code" => "SM", "phone_code" => "+378", "phone_digits" => 10, "flag" => "🇸🇲"],
            ["name" => "Sao Tome and Principe", "iso_code" => "ST", "phone_code" => "+239", "phone_digits" => 7, "flag" => "🇸🇹"],
            ["name" => "Saudi Arabia", "iso_code" => "SA", "phone_code" => "+966", "phone_digits" => 9, "flag" => "🇸🇦"],
            ["name" => "Senegal", "iso_code" => "SN", "phone_code" => "+221", "phone_digits" => 9, "flag" => "🇸🇳"],
            ["name" => "Serbia", "iso_code" => "RS", "phone_code" => "+381", "phone_digits" => 9, "flag" => "🇷🇸"],
            ["name" => "Seychelles", "iso_code" => "SC", "phone_code" => "+248", "phone_digits" => 7, "flag" => "🇸🇨"],
            ["name" => "Sierra Leone", "iso_code" => "SL", "phone_code" => "+232", "phone_digits" => 8, "flag" => "🇸🇱"],
            ["name" => "Singapore", "iso_code" => "SG", "phone_code" => "+65", "phone_digits" => 8, "flag" => "🇸🇬"],
            ["name" => "Slovakia", "iso_code" => "SK", "phone_code" => "+421", "phone_digits" => 9, "flag" => "🇸🇰"],
            ["name" => "Slovenia", "iso_code" => "SI", "phone_code" => "+386", "phone_digits" => 8, "flag" => "🇸🇮"],
            ["name" => "Solomon Islands", "iso_code" => "SB", "phone_code" => "+677", "phone_digits" => 7, "flag" => "🇸🇧"],
            ["name" => "Somalia", "iso_code" => "SO", "phone_code" => "+252", "phone_digits" => 8, "flag" => "🇸🇴"],
            ["name" => "South Africa", "iso_code" => "ZA", "phone_code" => "+27", "phone_digits" => 9, "flag" => "🇿🇦"],
            ["name" => "South Korea", "iso_code" => "KR", "phone_code" => "+82", "phone_digits" => 10, "flag" => "🇰🇷"],
            ["name" => "South Sudan", "iso_code" => "SS", "phone_code" => "+211", "phone_digits" => 9, "flag" => "🇸🇸"],
            ["name" => "Spain", "iso_code" => "ES", "phone_code" => "+34", "phone_digits" => 9, "flag" => "🇪🇸"],
            ["name" => "Sri Lanka", "iso_code" => "LK", "phone_code" => "+94", "phone_digits" => 9, "flag" => "🇱🇰"],
            ["name" => "Sudan", "iso_code" => "SD", "phone_code" => "+249", "phone_digits" => 9, "flag" => "🇸🇩"],
            ["name" => "Suriname", "iso_code" => "SR", "phone_code" => "+597", "phone_digits" => 7, "flag" => "🇸🇷"],
            ["name" => "Sweden", "iso_code" => "SE", "phone_code" => "+46", "phone_digits" => 9, "flag" => "🇸🇪"],
            ["name" => "Switzerland", "iso_code" => "CH", "phone_code" => "+41", "phone_digits" => 9, "flag" => "🇨🇭"],
            ["name" => "Syria", "iso_code" => "SY", "phone_code" => "+963", "phone_digits" => 9, "flag" => "🇸🇾"],
            ["name" => "Taiwan", "iso_code" => "TW", "phone_code" => "+886", "phone_digits" => 9, "flag" => "🇹🇼"],
            ["name" => "Tajikistan", "iso_code" => "TJ", "phone_code" => "+992", "phone_digits" => 9, "flag" => "🇹🇯"],
            ["name" => "Tanzania", "iso_code" => "TZ", "phone_code" => "+255", "phone_digits" => 9, "flag" => "🇹🇿"],
            ["name" => "Thailand", "iso_code" => "TH", "phone_code" => "+66", "phone_digits" => 9, "flag" => "🇹🇭"],
            ["name" => "Togo", "iso_code" => "TG", "phone_code" => "+228", "phone_digits" => 8, "flag" => "🇹🇬"],
            ["name" => "Tonga", "iso_code" => "TO", "phone_code" => "+676", "phone_digits" => 5, "flag" => "🇹🇴"],
            ["name" => "Trinidad and Tobago", "iso_code" => "TT", "phone_code" => "+1868", "phone_digits" => 7, "flag" => "🇹🇹"],
            ["name" => "Tunisia", "iso_code" => "TN", "phone_code" => "+216", "phone_digits" => 8, "flag" => "🇹🇳"],
            ["name" => "Turkey", "iso_code" => "TR", "phone_code" => "+90", "phone_digits" => 10, "flag" => "🇹🇷"],
            ["name" => "Turkmenistan", "iso_code" => "TM", "phone_code" => "+993", "phone_digits" => 8, "flag" => "🇹🇲"],
            ["name" => "Tuvalu", "iso_code" => "TV", "phone_code" => "+688", "phone_digits" => 5, "flag" => "🇹🇻"],
            ["name" => "Uganda", "iso_code" => "UG", "phone_code" => "+256", "phone_digits" => 9, "flag" => "🇺🇬"],
            ["name" => "Ukraine", "iso_code" => "UA", "phone_code" => "+380", "phone_digits" => 9, "flag" => "🇺🇦"],
            ["name" => "United Arab Emirates", "iso_code" => "AE", "phone_code" => "+971", "phone_digits" => 9, "flag" => "🇦🇪"],
            ["name" => "United Kingdom", "iso_code" => "GB", "phone_code" => "+44", "phone_digits" => 10, "flag" => "🇬🇧"],
            ["name" => "United States", "iso_code" => "US", "phone_code" => "+1", "phone_digits" => 10, "flag" => "🇺🇸"],
            ["name" => "Uruguay", "iso_code" => "UY", "phone_code" => "+598", "phone_digits" => 8, "flag" => "🇺🇾"],
            ["name" => "Uzbekistan", "iso_code" => "UZ", "phone_code" => "+998", "phone_digits" => 9, "flag" => "🇺🇿"],
            ["name" => "Vanuatu", "iso_code" => "VU", "phone_code" => "+678", "phone_digits" => 7, "flag" => "🇻🇺"],
            ["name" => "Vatican", "iso_code" => "VA", "phone_code" => "+39", "phone_digits" => 10, "flag" => "🇻🇦"],
            ["name" => "Venezuela", "iso_code" => "VE", "phone_code" => "+58", "phone_digits" => 10, "flag" => "🇻🇪"],
            ["name" => "Vietnam", "iso_code" => "VN", "phone_code" => "+84", "phone_digits" => 9, "flag" => "🇻🇳"],
            ["name" => "Yemen", "iso_code" => "YE", "phone_code" => "+967", "phone_digits" => 9, "flag" => "🇾🇪"],
            ["name" => "Zambia", "iso_code" => "ZM", "phone_code" => "+260", "phone_digits" => 9, "flag" => "🇿🇲"],
            ["name" => "Zimbabwe", "iso_code" => "ZW", "phone_code" => "+263", "phone_digits" => 9, "flag" => "🇿🇼"]
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(['iso_code' => $country['iso_code']], $country);
        }
    }
}
